title: Logan Cooley # your name (or website title) here
logo: "/images/TapeDismantled.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me
  <br>I work so that people and information can find each other. Across my experiences in 
  libraries, archives, and educational institutions, it’s been my privilege to work on behalf of 
  information per se and on behalf of people seeking information.<br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
